dist: bionic
sudo: true
language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - 3.8
stages:
  - lint
  - test
jobs:
  include:
    - { stage: lint, env: TOXENV=lint, python: 3.6 }

script:
    - tox
install:
    - pip install tox tox-travis
